# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MSLiveBox' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for MSLiveBox
  pod 'MJRefresh', '~> 3.1.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJExtension', '~> 3.0.13'
  pod 'Masonry', '~> 1.0.0'
  pod 'SDWebImage', '~> 3.7.5'
  target 'MSLiveBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MSLiveBoxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
